# Generated by Django 2.1 on 2018-09-06 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(blank=True, null=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('raw', models.BooleanField(default=False, help_text='Toggles parsing of markdown & display of styling')),
                ('edited_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_edited_by', to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_parent_page', to='pages.Page')),
            ],
        ),
    ]
