# Generated by Django 2.1 on 2018-09-06 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Format as hh:mm:ss')),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('attire', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('list_date', models.DateField(blank=True, help_text='Date that the event should be added to the availability listing. Leaving this blank will add it 30 days prior to the start.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('max_volunteers', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.VolunteerType'),
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
