# Generated by Django 3.0.4 on 2020-03-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=128)),
                ('start_date_time', models.DateTimeField(help_text='Date and time of the start of the event')),
                ('duration', models.DurationField(help_text='Duration of the event')),
                ('location', models.CharField(help_text='Location of the event', max_length=128)),
                ('details', models.TextField(blank=True, help_text='Additional details of the event', null=True)),
                ('display_on_date_time', models.DateField(blank=True, help_text='Date and time to begin displaying the event to volunteers', null=True)),
                ('lock_in', models.DurationField(help_text='Duration prior to the event during which volunteers may not cancel')),
                ('installation', models.ForeignKey(help_text='Reference to the installation at which the event is occurring', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
        migrations.CreateModel(
            name='EventPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_volunteers', models.IntegerField(help_text='Maximum number of volunteers for the position')),
                ('instructions', models.TextField(help_text='Instructions for the volunteers regarding their position')),
                ('required_installation_group', models.ForeignKey(help_text='The installation group the volunteer must belong to to volunteer for the position', on_delete=django.db.models.deletion.CASCADE, to='installations.InstallationGroup')),
            ],
        ),
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False, help_text='True if volunteer has identified themselves as "ready" for the event')),
                ('event', models.ForeignKey(help_text='The event being volunteered for', on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('event_position', models.ForeignKey(help_text='The position being volunteered for', on_delete=django.db.models.deletion.CASCADE, to='events.EventPosition')),
                ('volunteer', models.ForeignKey(help_text='The Volunteer for the event', on_delete=django.db.models.deletion.CASCADE, to='installations.InstallationVolunteer')),
            ],
        ),
    ]
