# Generated by Django 2.2.7 on 2019-12-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=128)),
                ('details', models.TextField(blank=True, null=True)),
                ('display_on', models.DateField(blank=True, null=True)),
                ('lock_in', models.DurationField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_volunteers', models.IntegerField(max_length=5)),
                ('instructions', models.TextField()),
                ('required_installation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.InstallationGroup')),
            ],
        ),
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False, help_text='True if volunteer has identified themselves as "ready" for the event')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
                ('volunteer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.VolunteerType')),
            ],
        ),
    ]
