# Generated by Django 2.2.7 on 2019-12-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteertype',
            name='max_volunteers',
            field=models.IntegerField(),
        ),
    ]
