version: '3'

services:
  # TEMP: Using SQLite3 for now
  # db:
  #   build: docker/mysql/.
  #   volumes:
  #     - ./db:/var/lib/mysql

  django_migration:
    build: docker/django/.
    working_dir: /srv
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate"
    volumes:
      - .:/srv
    # depends_on:
      # - db

  django:
    build: docker/django/.
    working_dir: /srv
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/srv
    ports:
      - "8000:8000"
    depends_on:
      - django_migration