# Generated by Django 3.0.4 on 2020-03-22 21:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.ForeignKey(help_text='Installation the news belongs to', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticleEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The new title of the news article', max_length=128)),
                ('content', models.TextField(help_text='The new news article content')),
                ('edited_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time that the news article was edited')),
                ('article', models.ForeignKey(help_text='News article being edited', on_delete=django.db.models.deletion.CASCADE, to='news.NewsArticle')),
                ('edited_by', models.ForeignKey(help_text='Volunteer editing the news article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.Volunteer')),
            ],
        ),
    ]
