# Generated by Django 3.0.4 on 2020-03-23 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False, help_text="True if the volunteer's email address has been verified")),
                ('email_key', models.CharField(help_text="Key for verifying a volunteer's email address", max_length=40)),
                ('key_expires', models.DateTimeField(help_text='The expiration date of the email verification key')),
                ('latitude', models.DecimalField(decimal_places=2, help_text='2 decimal places (~1km of GPS precision for privacy)', max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, help_text='2 decimal places (~1km of GPS precision for privacy)', max_digits=5)),
                ('globally_verified', models.BooleanField(default=False, help_text='True, if the volunteer has had their identity verified by ad2dispatch.\n                     Is not affected by installation-level verification.')),
                ('service', models.CharField(choices=[('USAF', 'Air Force'), ('ARMY', 'Army'), ('NAVY', 'Navy'), ('USMC', 'Marine Corps'), ('USCG', 'Coast Guard'), ('SPSE', 'Military Spouse'), ('GCIV', 'Government Civilian'), ('NONE', 'Other/Not Applicable')], help_text='The military service of the volunteer', max_length=4)),
                ('unit', models.CharField(help_text='The unit of the volunteer', max_length=128)),
                ('rank', models.CharField(choices=[('E1', 'E-1'), ('E2', 'E-2'), ('E3', 'E-3'), ('E4', 'E-4'), ('E5', 'E-5'), ('E6', 'E-6'), ('E7', 'E-7'), ('E8', 'E-8'), ('E9', 'E-9'), ('W1', 'W-1'), ('W2', 'W-2'), ('W3', 'W-3'), ('W4', 'W-4'), ('W5', 'W-5'), ('O1', 'O-1'), ('O2', 'O-2'), ('O3', 'O-3'), ('O4', 'O-4'), ('O5', 'O-5'), ('O6', 'O-6'), ('O7', 'O-7'), ('O8', 'O-8'), ('O9', 'O-9'), ('O10', 'O-10'), ('NONE', 'Other/Not Applicable')], help_text='The rank of the volunteer', max_length=4)),
                ('phone_number', models.CharField(help_text='The phone number of the volunteer', max_length=24)),
                ('phone_number_alt', models.CharField(help_text='The alternate phone number of the volunteer', max_length=24)),
                ('vehicle_description', models.CharField(help_text="The description of the volunteer's vehicle", max_length=256)),
                ('supervisor_name', models.CharField(help_text="The name of the volunteer's supervisor", max_length=128)),
                ('supervisor_phone_number', models.CharField(help_text="The phone number of the volunteer's supervisor", max_length=24)),
                ('dispatched', models.BooleanField(default=False, help_text='True if the volunteer is currently dispatched')),
                ('profile_reviewed', models.DateField(default=django.utils.timezone.now, help_text='True if the volunteer has reviewed their profile since the last change')),
                ('user', models.OneToOneField(help_text='User associated with the volunteer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
