# Generated by Django 3.0.4 on 2020-03-22 04:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.ForeignKey(help_text='Installation the page belongs to', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('parent_page', models.ForeignKey(help_text='Parent page of this page', on_delete=django.db.models.deletion.PROTECT, to='pages.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PageEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The new title of the page', max_length=128)),
                ('content', models.TextField(help_text='The new page content')),
                ('edited_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time that the page was edited')),
                ('edited_by', models.ForeignKey(help_text='Volunteer editing the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.Volunteer')),
                ('page', models.ForeignKey(help_text='Page being edited', on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
    ]
