# Generated by Django 2.1.1 on 2019-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
