# Generated by Django 2.1.1 on 2019-01-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': (), 'permissions': (('view_hidden_events', 'Can view hidden events'), ('vol_hidden_events', 'Can volunteer for hidden events'))},
        ),
        migrations.AlterModelOptions(
            name='eventvolunteer',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='volunteertype',
            options={'default_permissions': ()},
        ),
    ]
