# Generated by Django 2.1.1 on 2019-05-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190209_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.ManyToManyField(to='events.VolunteerType'),
        ),
    ]
