# Generated by Django 2.1.1 on 2019-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190501_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteertype',
            name='default',
            field=models.BooleanField(default=False, help_text='If checked, this type will be added to new events by default. Assumes Common'),
        ),
    ]
