# Generated by Django 2.1.1 on 2019-05-02 00:33

from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190501_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertype',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='types',
            field=models.ManyToManyField(default=events.models.default_types, limit_choices_to=events.models.common_or_recent_types, to='events.VolunteerType'),
        ),
        migrations.AlterField(
            model_name='volunteertype',
            name='type',
            field=models.CharField(help_text='Name of volunteer type', max_length=16),
        ),
    ]
