# Generated by Django 2.1.5 on 2019-03-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_volunteer_accepted_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='reviewed_profile',
            field=models.BooleanField(default=False, help_text='If the volunteer has reviewed their profile since the last major update to profile fields'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
