# Generated by Django 2.1 on 2018-09-06 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='USAF', max_length=24, null=True)),
                ('rank', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=14, null=True)),
                ('vehicle_desc', models.CharField(max_length=128, null=True)),
                ('ready', models.BooleanField(default=False, help_text="If driver has marked themselves as 'ready' for the event duration.")),
                ('dispatched', models.BooleanField(default=False, editable=False)),
                ('council_pos', models.CharField(blank=True, max_length=24, null=True)),
                ('sup_name', models.CharField(max_length=64, null=True)),
                ('sup_phone', models.CharField(max_length=14, null=True)),
                ('location', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
