# Generated by Django 3.0.4 on 2020-03-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the installation organization', max_length=128)),
                ('slug', models.SlugField(help_text='The url slug of the installation. NOTE: Editing this field may break links')),
                ('latitude', models.DecimalField(decimal_places=3, help_text='3 decimal places (~100m of GPS precision)', max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, help_text='3 decimal places (~100m of GPS precision)', max_digits=6)),
                ('volunteer_policy', models.TextField(help_text='Organizational policy that all drivers must agree to prior to volunteering.\n                     May include standards on insurance, vehicle safety measures, liability, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the installation group', max_length=128)),
                ('can_mod_config', models.BooleanField(help_text='True if the group can modify the installation organization configuration')),
                ('can_mod_pages', models.BooleanField(help_text="True if the group can modify the installation organization's pages")),
                ('can_mod_news', models.BooleanField(help_text="True if the group can modify the installation organization's news articles")),
                ('can_mod_volunteers', models.BooleanField(help_text="True if the group can modify the installation organization volunteers' statuses")),
                ('can_verify_volunteers', models.BooleanField(help_text='True if the group can verify volunteers at the installation organization level')),
                ('installation', models.ForeignKey(help_text='Installation the group belongs to', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the position', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Description of the duties of the position', null=True)),
                ('can_mod_config', models.BooleanField(help_text='True if the position can modify the installation organization configuration')),
                ('can_mod_pages', models.BooleanField(help_text="True if the position can modify the installation organization's pages")),
                ('can_mod_news', models.BooleanField(help_text="True if the position can modify the installation organization's news articles")),
                ('can_mod_volunteers', models.BooleanField(help_text="True if the position can modify the installation organization volunteers' statuses")),
                ('can_verify_volunteers', models.BooleanField(help_text='True if the position can verify volunteers at the installation organization level')),
                ('installation', models.ForeignKey(help_text='Installation the position belongs to', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationVolunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_verified', models.BooleanField(default=False, help_text='True, if the installation organization has verified a volunteer.\n                     Installation orgs cannot globally verify volunteers.')),
                ('accepted_policies', models.BooleanField(default=False, help_text="True, if the volunteer has accepted the installation's volunteering policies")),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPositionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(help_text="The date and time when the user's access to the group expires")),
                ('installation_position', models.ForeignKey(help_text='The installation position the volunteer holds', on_delete=django.db.models.deletion.CASCADE, to='installations.InstallationPosition')),
                ('volunteer', models.ForeignKey(help_text='The volunteer is the installation position', on_delete=django.db.models.deletion.CASCADE, to='installations.InstallationVolunteer')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(help_text="The date and time when the user's access to the group expires")),
                ('installation_group', models.ForeignKey(help_text='The installation group the volunteer is in', on_delete=django.db.models.deletion.CASCADE, to='installations.InstallationGroup')),
                ('volunteer', models.ForeignKey(help_text='The volunteer in the installation group', on_delete=django.db.models.deletion.CASCADE, to='installations.InstallationVolunteer')),
            ],
        ),
    ]
